auth_enabled: false  # Loki's built-in auth is disabled

server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0  # use 0.0.0.0 to listen on all interfaces
  log_level: debug
  grpc_listen_port: 9095
  grpc_listen_address: 127.0.0.1

frontend:
  address: 127.0.0.1
  port: 9095
  max_outstanding_per_tenant: 500
  compress_responses: true

frontend_worker:
  frontend_address: 127.0.0.1:9095
  grpc_client_config:
    max_send_msg_size: 104857600
    max_recv_msg_size: 104857600

querier:
  max_concurrent: 10
  engine:
    max_look_back_period: 5m

common:
  storage:
    filesystem:
      chunks_directory: /data/loki/chunks
      rules_directory: /data/loki/rules
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /data/loki/tsdb
    cache_location: /data/loki/tsdb-cache
  filesystem:
    directory: /data/loki/chunks

compactor:
  working_directory: /data/loki/compactor

limits_config:
  split_queries_by_interval: 15m
  max_query_series: 500
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_entries_limit_per_query: 5000
  allow_structured_metadata: true

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: /data/loki/wal
